name: 50states
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- numpy=1.13.3=py36h2cdce51_0
- jinja2=2.9.6=py36_0
- markupsafe=1.0=py36_0
- mplleaflet=0.0.5=py36_1
- appnope=0.1.0=py36hf537a9a_0
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2017.7.27.1=py36hd973bb6_0
- cycler=0.10.0=py36hfc81398_0
- decorator=4.1.2=py36h69a1b52_0
- freetype=2.8=h143eb01_0
- intel-openmp=2018.0.0=h68bdfb3_7
- ipykernel=4.6.1=py36h3208c25_0
- ipython=6.1.0=py36hf612aae_1
- ipython_genutils=0.2.0=py36h241746c_0
- jedi=0.10.2=py36h6325097_0
- jupyter_client=5.1.0=py36hf6c435f_0
- jupyter_core=4.3.0=py36h93810fe_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=hd939716_3
- libgfortran=3.0.1=h93005f0_2
- libpng=1.6.32=h6184301_3
- libsodium=1.0.13=hba5e272_2
- matplotlib=2.1.0=py36h5068139_0
- mkl=2018.0.0=h5ef208c_6
- ncurses=6.0=ha932d30_1
- networkx=2.0=py36hefccab9_0
- openssl=1.0.2m=h86d3e6a_0
- pandas=0.21.0=py36hfed917e_1
- pexpect=4.2.1=py36h3eac828_0
- pickleshare=0.7.4=py36hf512f8e_0
- pip=9.0.1=py36h1555ced_4
- prompt_toolkit=1.0.15=py36haeda067_0
- ptyprocess=0.5.2=py36he6521c3_0
- pygments=2.2.0=py36h240cd3f_0
- pyparsing=2.2.0=py36hb281f35_0
- python=3.6.3=hc655967_3
- python-dateutil=2.6.1=py36h86d2abb_1
- pytz=2017.2=py36h2e7dfbc_1
- pyzmq=16.0.2=py36h087ffad_2
- readline=7.0=h81b24a6_3
- setuptools=36.5.0=py36h2134326_0
- simplegeneric=0.8.1=py36he5b5b09_0
- six=1.11.0=py36h0e22d5e_1
- sqlite=3.20.1=h900c3b0_1
- tk=8.6.7=hcdce994_1
- tornado=4.5.2=py36h468dda9_0
- traitlets=4.3.2=py36h65bd3ce_0
- wcwidth=0.1.7=py36h8c6ec74_0
- wheel=0.29.0=py36h3597b6d_1
- xz=5.2.3=ha24016e_1
- zeromq=4.2.2=h131e0f7_1
- zlib=1.2.11=h60db283_1
- pip:
  - click==6.7
  - click-plugins==1.0.3
  - cligj==0.4.0
  - descartes==1.1.0
  - fiona==1.7.10.post1
  - geopandas==0.3.0
  - ipython-genutils==0.2.0
  - jsonschema==2.6.0
  - jupyter-client==5.1.0
  - jupyter-core==4.4.0
  - munch==2.2.0
  - nbformat==4.4.0
  - postman-problems==0.2
  - prompt-toolkit==1.0.15
  - pyproj==1.9.5.1
  - shapely==1.6.2.post1
